name: Update Changelog Index

on:
  push:
    branches:
      - main
    paths:
      - 'n8nmanager/changelogs/*.md'

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install markdown

      - name: Generate changelog HTML
        run: |
          python3 scripts/generate-changelog-html.py

      - name: Update sitemap
        run: |
          python3 scripts/update-sitemap-changelog.py

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet n8nmanager/changelog.html n8nmanager/sitemap.xml; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add n8nmanager/changelog.html n8nmanager/sitemap.xml
          git commit -m "chore: auto-update changelog and sitemap ($(date '+%Y-%m-%d'))"
          git push
